package com.demo.entities;
// Generated May 8, 2024, 3:01:13 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;


/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "bachu_database", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "username") })
public class Account implements java.io.Serializable {

	private Integer accountId;
	private Role role;
	private String username;
	private String email;
	private String password;
	private boolean status;
	private String token;
	private String securityCode;
	private Set<Album> albums = new HashSet<>(0);
	private Set<Notification> notifications = new HashSet<>(0);
	private Set<AccountSong> accountSongs = new HashSet<>(0);
	private Set<Userprofile> userprofiles = new HashSet<>(0);
	private Set<Accountmembership> accountmemberships = new HashSet<>(0);
	private Set<Transactionhistory> transactionhistories = new HashSet<>(0);

	public Account() {
	}

	public Account(String username, String email, String password, boolean status) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.status = status;
	}

	public Account(Role role, String username, String email, String password, boolean status, String token,
			String securityCode, Set<Album> albums, Set<Notification> notifications, Set<AccountSong> accountSongs,
			Set<Userprofile> userprofiles, Set<Accountmembership> accountmemberships,
			Set<Transactionhistory> transactionhistories) {
		this.role = role;
		this.username = username;
		this.email = email;
		this.password = password;
		this.status = status;
		this.token = token;
		this.securityCode = securityCode;
		this.albums = albums;
		this.notifications = notifications;
		this.accountSongs = accountSongs;
		this.userprofiles = userprofiles;
		this.accountmemberships = accountmemberships;
		this.transactionhistories = transactionhistories;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "account_id", unique = true, nullable = false)
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "security_code")
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<AccountSong> getAccountSongs() {
		return this.accountSongs;
	}

	public void setAccountSongs(Set<AccountSong> accountSongs) {
		this.accountSongs = accountSongs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Userprofile> getUserprofiles() {
		return this.userprofiles;
	}

	public void setUserprofiles(Set<Userprofile> userprofiles) {
		this.userprofiles = userprofiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Accountmembership> getAccountmemberships() {
		return this.accountmemberships;
	}

	public void setAccountmemberships(Set<Accountmembership> accountmemberships) {
		this.accountmemberships = accountmemberships;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Transactionhistory> getTransactionhistories() {
		return this.transactionhistories;
	}

	public void setTransactionhistories(Set<Transactionhistory> transactionhistories) {
		this.transactionhistories = transactionhistories;
	}

}
