package com.demo.entities;
// Generated Apr 23, 2024, 10:45:04 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Accountverification generated by hbm2java
 */
@Entity
@Table(name = "accountverification", catalog = "music_app")
public class Accountverification implements java.io.Serializable {

	private Integer verificationId;
	private Account account;
	private String verificationCode;
	private Integer isVerified;

	public Accountverification() {
	}

	public Accountverification(Account account, String verificationCode, Integer isVerified) {
		this.account = account;
		this.verificationCode = verificationCode;
		this.isVerified = isVerified;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "verification_id", unique = true, nullable = false)
	public Integer getVerificationId() {
		return this.verificationId;
	}

	public void setVerificationId(Integer verificationId) {
		this.verificationId = verificationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "verification_code")
	public String getVerificationCode() {
		return this.verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	@Column(name = "is_verified")
	public Integer getIsVerified() {
		return this.isVerified;
	}

	public void setIsVerified(Integer isVerified) {
		this.isVerified = isVerified;
	}

}
