package com.demo.entities;
// Generated May 3, 2024, 7:07:39 PM by Hibernate Tools 4.3.6.Final

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Accountmembership generated by hbm2java
 */
@Entity
@Table(name = "accountmembership", catalog = "bachu_database")
public class Accountmembership implements java.io.Serializable {

	private Integer accountMembershipId;
	private Account account;
	private Membershippackage membershippackage;
	private Date startDate;
	private Date endDate;

	public Accountmembership() {
	}

	public Accountmembership(Account account, Membershippackage membershippackage, Date startDate, Date endDate) {
		this.account = account;
		this.membershippackage = membershippackage;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "account_membership_id", unique = true, nullable = false)
	public Integer getAccountMembershipId() {
		return this.accountMembershipId;
	}

	public void setAccountMembershipId(Integer accountMembershipId) {
		this.accountMembershipId = accountMembershipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_id")
	public Membershippackage getMembershippackage() {
		return this.membershippackage;
	}

	public void setMembershippackage(Membershippackage membershippackage) {
		this.membershippackage = membershippackage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
