package com.demo.entities;
// Generated Apr 23, 2024, 10:45:04 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * AccountSong generated by hbm2java
 */
@Entity
@Table(name = "account_song", catalog = "music_app")
public class AccountSong implements java.io.Serializable {

	private Integer accountSongId;
	private Account account;
	private Song song;
	private Date postDate;

	public AccountSong() {
	}

	public AccountSong(Account account, Song song, Date postDate) {
		this.account = account;
		this.song = song;
		this.postDate = postDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "account_song_id", unique = true, nullable = false)
	public Integer getAccountSongId() {
		return this.accountSongId;
	}

	public void setAccountSongId(Integer accountSongId) {
		this.accountSongId = accountSongId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id")
	public Song getSong() {
		return this.song;
	}

	public void setSong(Song song) {
		this.song = song;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_date", length = 19)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

}
