package com.demo.entities;
// Generated May 3, 2024, 8:30:25 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "bachu_database")
public class Album implements java.io.Serializable {

	private Integer albumId;
	private Account account;
	private String albumName;
	private Date releaseDate;
	private String albumCoverUrl;
	private Set<AccountSong> accountSongs = new HashSet<>(0);
	private Set<Song> songs = new HashSet<>(0);
	private Set<Song> songs_1 = new HashSet<>(0);

	public Album() {
	}

	public Album(String albumName) {
		this.albumName = albumName;
	}

	public Album(Account account, String albumName, Date releaseDate, String albumCoverUrl,
			Set<AccountSong> accountSongs, Set<Song> songs, Set<Song> songs_1) {
		this.account = account;
		this.albumName = albumName;
		this.releaseDate = releaseDate;
		this.albumCoverUrl = albumCoverUrl;
		this.accountSongs = accountSongs;
		this.songs = songs;
		this.songs_1 = songs_1;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "album_id", unique = true, nullable = false)
	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "album_name", nullable = false)
	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "album_cover_url")
	public String getAlbumCoverUrl() {
		return this.albumCoverUrl;
	}

	public void setAlbumCoverUrl(String albumCoverUrl) {
		this.albumCoverUrl = albumCoverUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<AccountSong> getAccountSongs() {
		return this.accountSongs;
	}

	public void setAccountSongs(Set<AccountSong> accountSongs) {
		this.accountSongs = accountSongs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "album_song", catalog = "bachu_database", joinColumns = {
			@JoinColumn(name = "album_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "song_id", nullable = false, updatable = false) })
	public Set<Song> getSongs() {
		return this.songs;
	}

	public void setSongs(Set<Song> songs) {
		this.songs = songs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<Song> getSongs_1() {
		return this.songs_1;
	}

	public void setSongs_1(Set<Song> songs_1) {
		this.songs_1 = songs_1;
	}

}
