package com.demo.entities;
// Generated May 8, 2024, 3:01:13 PM by Hibernate Tools 4.3.6.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "bachu_database")
public class Comment implements java.io.Serializable {

	private Integer commentId;
	private AccountSong accountSong;
	private String commentText;
	private Date commentDate;

	public Comment() {
	}

	public Comment(AccountSong accountSong, String commentText, Date commentDate) {
		this.accountSong = accountSong;
		this.commentText = commentText;
		this.commentDate = commentDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "comment_id", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_song_id")
	public AccountSong getAccountSong() {
		return this.accountSong;
	}

	public void setAccountSong(AccountSong accountSong) {
		this.accountSong = accountSong;
	}

	@Column(name = "comment_text")
	public String getCommentText() {
		return this.commentText;
	}

	public void setCommentText(String commentText) {
		this.commentText = commentText;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "comment_date", length = 10)
	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

}
