package com.demo.entities;
// Generated May 3, 2024, 7:07:39 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Membershippackage generated by hbm2java
 */
@Entity
@Table(name = "membershippackage", catalog = "bachu_database", uniqueConstraints = @UniqueConstraint(columnNames = "package_name"))
public class Membershippackage implements java.io.Serializable {

	private Integer packageId;
	private String packageName;
	private Integer duration;
	private BigDecimal price;
	private Set<Transactionhistory> transactionhistories = new HashSet<>(0);
	private Set<Accountmembership> accountmemberships = new HashSet<>(0);

	public Membershippackage() {
	}

	public Membershippackage(String packageName) {
		this.packageName = packageName;
	}

	public Membershippackage(String packageName, Integer duration, BigDecimal price,
			Set<Transactionhistory> transactionhistories, Set<Accountmembership> accountmemberships) {
		this.packageName = packageName;
		this.duration = duration;
		this.price = price;
		this.transactionhistories = transactionhistories;
		this.accountmemberships = accountmemberships;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "package_id", unique = true, nullable = false)
	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	@Column(name = "package_name", unique = true, nullable = false, length = 100)
	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membershippackage")
	public Set<Transactionhistory> getTransactionhistories() {
		return this.transactionhistories;
	}

	public void setTransactionhistories(Set<Transactionhistory> transactionhistories) {
		this.transactionhistories = transactionhistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membershippackage")
	public Set<Accountmembership> getAccountmemberships() {
		return this.accountmemberships;
	}

	public void setAccountmemberships(Set<Accountmembership> accountmemberships) {
		this.accountmemberships = accountmemberships;
	}

}
