package com.demo.entities;
// Generated Apr 19, 2024, 7:07:22 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;


/**
 * Music generated by hbm2java
 */
@Entity
@Table(name = "music", catalog = "app_web_musics_database")
public class Music implements java.io.Serializable {

	private Integer id;
	private String name;
	private int authorId;
	private String image;
	private String file;
	private String album;
	private Date postingDate;
	private Date modifyDate;
	private String time;
	private boolean status;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Rating> ratings = new HashSet<Rating>(0);

	public Music() {
	}

	public Music(String name, int authorId, String album, Date postingDate, String time, boolean status) {
		this.name = name;
		this.authorId = authorId;
		this.album = album;
		this.postingDate = postingDate;
		this.time = time;
		this.status = status;
	}

	public Music(String name, int authorId, String image, String file, String album, Date postingDate, Date modifyDate,
			String time, boolean status, Set<Comment> comments, Set<Rating> ratings) {
		this.name = name;
		this.authorId = authorId;
		this.image = image;
		this.file = file;
		this.album = album;
		this.postingDate = postingDate;
		this.modifyDate = modifyDate;
		this.time = time;
		this.status = status;
		this.comments = comments;
		this.ratings = ratings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "authorId", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "file")
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Column(name = "album", nullable = false)
	public String getAlbum() {
		return this.album;
	}

	public void setAlbum(String album) {
		this.album = album;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "postingDate", nullable = false, length = 10)
	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifyDate", length = 10)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "time", nullable = false, length = 10)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "music")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "music")
	public Set<Rating> getRatings() {
		return this.ratings;
	}

	public void setRatings(Set<Rating> ratings) {
		this.ratings = ratings;
	}

}
