package com.demo.entities;
// Generated May 8, 2024, 3:01:13 PM by Hibernate Tools 4.3.6.Final

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "bachu_database")
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	private Transactionhistory transactionhistory;
	private Date paymentDate;
	private Float amount;
	private String paymentMethod;

	public Payment() {
	}

	public Payment(Transactionhistory transactionhistory, Date paymentDate, Float amount, String paymentMethod) {
		this.transactionhistory = transactionhistory;
		this.paymentDate = paymentDate;
		this.amount = amount;
		this.paymentMethod = paymentMethod;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "payment_id", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaction_id")
	public Transactionhistory getTransactionhistory() {
		return this.transactionhistory;
	}

	public void setTransactionhistory(Transactionhistory transactionhistory) {
		this.transactionhistory = transactionhistory;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "amount", precision = 12, scale = 0)
	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	@Column(name = "payment_method", length = 100)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

}
