package com.demo.entities;
// Generated May 3, 2024, 7:07:39 PM by Hibernate Tools 4.3.6.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Songdetail generated by hbm2java
 */
@Entity
@Table(name = "songdetail", catalog = "bachu_database")
public class Songdetail implements java.io.Serializable {

	private Integer songDetailId;
	private String title;
	private String lyric;
	private Date songTime;
	private String genre;
	private Date releaseDate;
	private String fileUrl;
	private Integer listenCount;
	private Integer status;
	private String songCoverUrl;
	private Set<Song> songs = new HashSet<>(0);

	public Songdetail() {
	}

	public Songdetail(String title) {
		this.title = title;
	}

	public Songdetail(String title, String lyric, Date songTime, String genre, Date releaseDate, String fileUrl,
			Integer listenCount, Integer status, String songCoverUrl, Set<Song> songs) {
		this.title = title;
		this.lyric = lyric;
		this.songTime = songTime;
		this.genre = genre;
		this.releaseDate = releaseDate;
		this.fileUrl = fileUrl;
		this.listenCount = listenCount;
		this.status = status;
		this.songCoverUrl = songCoverUrl;
		this.songs = songs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "song_detail_id", unique = true, nullable = false)
	public Integer getSongDetailId() {
		return this.songDetailId;
	}

	public void setSongDetailId(Integer songDetailId) {
		this.songDetailId = songDetailId;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "lyric")
	public String getLyric() {
		return this.lyric;
	}

	public void setLyric(String lyric) {
		this.lyric = lyric;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "song_time", length = 8)
	public Date getSongTime() {
		return this.songTime;
	}

	public void setSongTime(Date songTime) {
		this.songTime = songTime;
	}

	@Column(name = "genre", length = 50)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "file_url")
	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	@Column(name = "listen_count")
	public Integer getListenCount() {
		return this.listenCount;
	}

	public void setListenCount(Integer listenCount) {
		this.listenCount = listenCount;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "song_cover_url")
	public String getSongCoverUrl() {
		return this.songCoverUrl;
	}

	public void setSongCoverUrl(String songCoverUrl) {
		this.songCoverUrl = songCoverUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "songdetail")
	public Set<Song> getSongs() {
		return this.songs;
	}

	public void setSongs(Set<Song> songs) {
		this.songs = songs;
	}

}
