package com.demo.entities;
// Generated Apr 23, 2024, 10:45:04 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Songdetail generated by hbm2java
 */
@Entity
@Table(name = "songdetail", catalog = "music_app")
public class Songdetail implements java.io.Serializable {

	private Integer songDetailId;
	private String title;
	private String genre;
	private Date releaseDate;
	private String fileUrl;
	private Integer listenCount;
	private Integer status;
	private Set<Song> songs = new HashSet<Song>(0);

	public Songdetail() {
	}

	public Songdetail(String title) {
		this.title = title;
	}

	public Songdetail(String title, String genre, Date releaseDate, String fileUrl, Integer listenCount, Integer status,
			Set<Song> songs) {
		this.title = title;
		this.genre = genre;
		this.releaseDate = releaseDate;
		this.fileUrl = fileUrl;
		this.listenCount = listenCount;
		this.status = status;
		this.songs = songs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "song_detail_id", unique = true, nullable = false)
	public Integer getSongDetailId() {
		return this.songDetailId;
	}

	public void setSongDetailId(Integer songDetailId) {
		this.songDetailId = songDetailId;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "genre", length = 50)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "file_url")
	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	@Column(name = "listen_count")
	public Integer getListenCount() {
		return this.listenCount;
	}

	public void setListenCount(Integer listenCount) {
		this.listenCount = listenCount;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "songdetail")
	public Set<Song> getSongs() {
		return this.songs;
	}

	public void setSongs(Set<Song> songs) {
		this.songs = songs;
	}

}
