package com.demo.entities;
// Generated Apr 23, 2024, 10:45:04 AM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Transactionhistory generated by hbm2java
 */
@Entity
@Table(name = "transactionhistory", catalog = "music_app")
public class Transactionhistory implements java.io.Serializable {

	private Integer transactionId;
	private Account account;
	private Membershippackage membershippackage;
	private Date transactionDate;
	private BigDecimal amount;
	private Set<Payment> payments = new HashSet<>(0);

	public Transactionhistory() {
	}

	public Transactionhistory(Account account, Membershippackage membershippackage, Date transactionDate,
			BigDecimal amount, Set<Payment> payments) {
		this.account = account;
		this.membershippackage = membershippackage;
		this.transactionDate = transactionDate;
		this.amount = amount;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "transaction_id", unique = true, nullable = false)
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_id")
	public Membershippackage getMembershippackage() {
		return this.membershippackage;
	}

	public void setMembershippackage(Membershippackage membershippackage) {
		this.membershippackage = membershippackage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transaction_date", length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionhistory")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
