package com.demo.entitiesjpa;
// Generated Aug 18, 2023, 2:33:02 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account")
public class Account implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private String displayName;
	private String gender;
	private boolean status;
	//private String securityCode;
	private Date dob;

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

//	@Column(name = "security_code", nullable = false, length = 250)
//	public String getSecurityCode() {
//		return securityCode;
//	}
//
//	public void setSecurityCode(String securityCode) {
//		this.securityCode = securityCode;
//	}

	public Account() {
	}

	public Account(String email, String password, String displayName, String gender, boolean status) {
		this.email = email;
		this.password = password;
		this.displayName = displayName;
		this.gender = gender;
		this.status = status;
	}

	public Account(String email, String password, String displayName, String gender, boolean status, Set<Role> roles,
			Set<Invoice> invoices) {
		this.email = email;
		this.password = password;
		this.displayName = displayName;
		this.gender = gender;
		this.status = status;
//		this.roles = roles;
//		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getemail() {
		return this.email;
	}

	public void setemail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "displayname", nullable = false, length = 250)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "gender", nullable = false, length = 250)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}
}
